application: hd-room-reservation
module: default
version: live
runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 500ms
  max_pending_latency: 2.0s

default_expiration: "7d"

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static/
  static_dir: static

- url: /.*
  script: main.app
